server:
  port: 8761

spring:
  zipkin:
    base-url: http://zipkin-server:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "health"
  tracing:
    sampling:
      base-url: http://zipkin-server:9411
      probability: 1