server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

spring:
  zipkin:
    base-url: http://zipkin-server:9411
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health"
  tracing:
    sampling:
      base-url: http://zipkin-server:9411
      probability: 1