# Server configuration
server:
  port: 8100

# Eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Gateway configuration
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "health"

# Logging configuration
logging:
  level:
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
    com.medilabo.gatewayserver.filter.AuthorizationFilter: DEBUG

# Property to configure the health check endpoint
healthcheck:
  endpoint: "/actuator/health"