# Server configuration
server:
  port: 8100
  server:
    compression:
      enabled: true
      min-response-size: 1024
      mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json, application/xml

# Eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

# Gateway configuration
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "health"

# Property to configure the health check endpoint
healthcheck:
  endpoint: "/actuator/health"