server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health"

logging:
  level:
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
    com.medilabo.gatewayserver.filter.AuthorizationFilter: DEBUG

health-check:
  path: "/actuator/health"