server:
    port: 9100

spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: notedb
            username: note_db_user_test
            password: note_db_password_test
            authentication-database: admin
            auto-index-creation: true

management:
    endpoints:
        web:
            exposure:
                include: "health"

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/