server:
    port: 9000

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/patientdb
        username: '{cipher}7bee9d1c5f0e35b8695d6583f7623fe21f6e25236d109da1233c10848dbd3ad7a1bd5a47be717f295bdffdab953c3cbf'
        password: '{cipher}ae29fe1d4e10f5528917a593ca1a1b32a0296593015e574a1bfc67de9e92a3670935723df5446aaa4924af1cdeb7e9a0'
    jpa:
        hibernate:
        ddl-auto: update
    security:
        user:
            name: '{cipher}b910a1dd8bf0eb7a18ada2c54c9302f8b79a3ef4d3b2ffc5c14aaa5ec09e8f50cb202b4a940929de8698efc34fa008ec'
            password: '{cipher}2e40c55ac84ed57fe06ce4466ce8bccce92d80e5368e9369e2527797877b6ca34a02d5ac50f53b78759a9b91c3d0adcb'
            roles: USER

management:
    endpoints:
        web:
            exposure:
                include: "health"

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

logging:
    level:
        org:
            hibernate:
                SQL: debug