spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/patientdb
        username: patient_db_user_test
        password: patient_db_password_test
    jpa:
        hibernate:
        ddl-auto: update
    server:
        port: 9000