server:
    port: 8080

spring:
    zipkin:
        base-url: http://zipkin-server:9411

management:
    endpoints:
        web:
            exposure:
                include: "health"
    tracing:
        sampling:
            base-url: http://zipkin-server:9411
            probability: 1

eureka:
    client:
        serviceUrl:
            defaultZone: http://discovery-server:8761/eureka/