server:
    port: 9200

spring:
    security:
        user:
            name: '{cipher}a071e5528d8b01f6f4022bf5001e6738482536de861dce1a07a90811cc16496ad9dc754952a68e30e6575c3abf09391f'
            password: '$2a$12$rsAHt/HX3Rj0oZzdqmNLlOajx29Vt.H3SPWe2cUKg3nRHBjkxyp5S'
            roles: SERVICE

feign:
    client:
        patient:
            username: '{cipher}b910a1dd8bf0eb7a18ada2c54c9302f8b79a3ef4d3b2ffc5c14aaa5ec09e8f50cb202b4a940929de8698efc34fa008ec'
            password: '{cipher}32129ed4965674f6ecf946517a4f400be66cd2a8d123f0b889df8ca121f46346e4d1a3fcba485542ea003756a24b1515'
        note:
            username: '{cipher}a3b19babee036cd810fbd884972e1c6ca1e1fc8e4d58ad74512cdd77eb0d130888296a3863a2ed9b3189028741fbcc3f'
            password: '{cipher}abb0ab8a0522eeadf5baf1110d3ec4686ba2772879b133b0553e1b17531ab3f89f4dbbe21d7b3250dc492726423b6d91'

riskTerms: 'Hémoglobine A1C|Microalbumine|Taille|Poids|Fumeur|Fumeuse|Anormal|Cholestérol|Vertige|Rechute|Réaction|Anticorps'

management:
    endpoints:
        web:
            exposure:
                include: "health"

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

logging:
    level:
        com.medilabo.microserviceassessment.service.AssessmentService: DEBUG